services:
  consul:
    image: consul:1.15
    container_name: consul
    command: consul agent -dev -client=0.0.0.0
    ports:
      - "8500:8500"

  postgres:
    image: postgres:16
    container_name: qb-postgres
    environment:
      POSTGRES_USER: qb_user
      POSTGRES_PASSWORD: qb_password
      POSTGRES_DB: qb_db
    ports:
      - "5432:5432"
    volumes:
      - qb-postgres-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U qb_user -d qb_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: apache/kafka:3.7.0
    container_name: qb-kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LISTENERS: >
        INTERNAL://:9092,
        EXTERNAL://:29092,
        CONTROLLER://:9093

      KAFKA_ADVERTISED_LISTENERS: >
        INTERNAL://qb-kafka:9092,
        EXTERNAL://localhost:29092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        INTERNAL:PLAINTEXT,
        EXTERNAL:PLAINTEXT,
        CONTROLLER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@qb-kafka:9093
      KAFKA_LOG_DIRS: /var/lib/kafka/data

    ports:
      - "9092:9092"
      - "29092:29092"


  ingestion-service:
    build:
      context: ./ingestion-service
      dockerfile: Dockerfile
    container_name: ingestion-service
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      consul:
        condition: service_started
    healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
        interval: 10s
        timeout: 3s
        retries: 5
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/qb_db
      SPRING_DATASOURCE_USERNAME: qb_user
      SPRING_DATASOURCE_PASSWORD: qb_password
    ports:
      - "8081:8081"

  order-simulator:
    build:
      context: ./order-simulator
      dockerfile: Dockerfile
    container_name: order-simulator
    environment:
      INGESTION_BASE_URL: http://ingestion-service:8081
      ORDER_COUNT: 100
      ORDER_DELAY_SECONDS: 1
    depends_on:
      ingestion-service:
        condition: service_healthy
    restart: "no"

  aggregation-service:
    build:
      context: ./aggregation-service
      dockerfile: Dockerfile
    container_name: aggregation-service
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      consul:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/qb_db
      SPRING_DATASOURCE_USERNAME: qb_user
      SPRING_DATASOURCE_PASSWORD: qb_password
    ports:
      - "8082:8082"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  qb-postgres-data:
