version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: qb-postgres
    environment:
      POSTGRES_USER: qb_user
      POSTGRES_PASSWORD: qb_password
      POSTGRES_DB: qb_db
    ports:
      - "5432:5432"
    volumes:
      - qb-postgres-data:/var/lib/postgresql/data

volumes:
  qb-postgres-data:
