services:
  postgres:
    image: postgres:16
    container_name: qb-postgres
    environment:
      POSTGRES_USER: qb_user
      POSTGRES_PASSWORD: qb_password
      POSTGRES_DB: qb_db
    ports:
      - "5432:5432"
    volumes:
      - qb-postgres-data:/var/lib/postgresql/data

  ingestion-service:
    image: ingestion-service:latest
    container_name: ingestion-service
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/qb_db
      SPRING_DATASOURCE_USERNAME: qb_user
      SPRING_DATASOURCE_PASSWORD: qb_password
    ports:
      - "8081:8081"

  order-simulator:
    build:
      context: ./order-simulator
      dockerfile: Dockerfile
    container_name: order-simulator
    depends_on:
      - ingestion-service
    environment:
      INGESTION_BASE_URL: http://ingestion-service:8081
      ORDER_COUNT: "50"
volumes:
  qb-postgres-data:
