services:
  postgres:
    image: postgres:16
    container_name: qb-postgres
    environment:
      POSTGRES_USER: qb_user
      POSTGRES_PASSWORD: qb_password
      POSTGRES_DB: qb_db
    ports:
      - "5432:5432"
    volumes:
      - qb-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U qb_user -d qb_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: apache/kafka:3.7.0
    container_name: qb-kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://qb-kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@qb-kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    ports:
      - "9092:9092"

  ingestion-service:
    image: ingestion-service:latest
    container_name: ingestion-service
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
        interval: 10s
        timeout: 3s
        retries: 5
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/qb_db
      SPRING_DATASOURCE_USERNAME: qb_user
      SPRING_DATASOURCE_PASSWORD: qb_password
    ports:
      - "8081:8081"

  order-simulator:
    build:
      context: .
      dockerfile: Dockerfile.order-simulator
    container_name: order-simulator
    environment:
      INGESTION_BASE_URL: http://ingestion-service:8081
      ORDER_COUNT: 100
      ORDER_DELAY_SECONDS: 1
    depends_on:
      ingestion-service:
        condition: service_healthy
    restart: "no"

volumes:
  qb-postgres-data:
